# Site Genel Bilgileri
site_name: T-DIGITAL DESING
site_description: Comprehensive documentation for my project
site_author: Kerim Turak
site_url: https://kerimturak.github.io/my-mkdocs-site

# Tema Ayarları (Material for MkDocs)
theme:
  name: 'material'
  palette:
      - scheme: slate  # Karanlık tema (Slate)
        primary: 'deep purple'
        accent: 'indigo'
        toggle:
          icon: material/lightbulb-outline  # Tema değiştirici için ikon
          name: Switch to light mode  # Karanlık moddan aydınlık moda geçişte gösterilecek metin
      - scheme: default  # Aydınlık tema (Default)
        primary: 'deep purple'
        accent: 'indigo'
        toggle:
          icon: material/lightbulb  # Aydınlık tema için ikon
          name: Switch to dark mode  # Aydınlık moddan karanlık moda geçişte gösterilecek metin
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: './images/tcore_back.png'  # Özel logo
  favicon: './images/tcore.png'  # Tarayıcı simgesi
  features:
    - navigation.tabs  # Sekmeli navigasyon
    - navigation.top  # Üst menüde gezinti
    - search.suggest  # Arama önerileri

# Eklentiler
plugins:
  - search:  # Arama motoru yapılandırması
      lang: en
      separator: '[\s\-]+'


# Gezinme (Navigasyon)
nav:
  - Home: index.md
  - About: about.md
  - User Guide:
      - Introduction: guide/introduction.md
      - Installation: guide/installation.md
      - Configuration: guide/configuration.md
      - Usage: guide/usage.md
  - API Documentation:
      - Overview: api/overview.md
      - Endpoints:
          - Users: api/users.md
          - Products: api/products.md
  - Tutorials:
      - Getting Started: tutorials/getting_started.md
      - Advanced Features: tutorials/advanced.md
  - Blog: blog/index.md

# SEO ve Sosyal Paylaşım
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kerimturak/tdigital-design/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kerimturak0/
  analytics:
    google: 'G-1Z793ME76P'  # Google Analytics ID
  canonical_url: https://tdigital-design.com/kerimturak/  # Ana URL
  site_description: 'A detailed project documentation with SEO optimizations.'
  site_author: 'Kerim Turak'
  consent:
      title: Cookie consent
      description: >- 
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
      cookies:
        analytics: Google Analytics 
        custom: Custom cookie
  locale: 'en'
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Turkish
      link: /tr/
      lang: tr

# Markdown Uzantıları (Gelişmiş Biçimlendirme)
markdown_extensions:
  - toc:               # Sayfa başına bir içindekiler tablosu ekler
      permalink: true  # Başlık bağlantıları ekler
  - footnotes          # Dipnotlar ekler
  - tables             # Gelişmiş tablo desteği sağlar
  - admonition         # Uyarı, ipucu, not gibi bilgi kutuları oluşturur
  - pymdownx.superfences  # Gelişmiş kod blokları ve içerikler için destek
  - pymdownx.details   # Açılır kapanır detay/özet bölümleri oluşturur
  - pymdownx.highlight # Gelişmiş kod vurgulama özellikleri sağlar
  - pymdownx.magiclink # URL'leri ve e-posta adreslerini otomatik olarak bağlantılara dönüştürür
  - pymdownx.tasklist  # Yapılacaklar listeleri oluşturur
  - pymdownx.emoji     # Emoji desteği ekler
  - attr_list          # HTML sınıfları ve stiller gibi öznitelikler eklemenizi sağlar
  - def_list           # Tanım listeleri oluşturmanızı sağlar
  - abbr               # Kısaltmalar ve açıklamalar ekler
  - smarty             # Otomatik tipografik düzeltmeler yapar (tırnak işaretleri, uzun tireler vb.)
  - codehilite         # Kod bloklarına sözdizimi vurgulama ekler
  - meta               # Sayfa başına meta veriler ekler


# Yayınlama Ayarları
repo_url: https://github.com/kerimturak/tdigital-design/  # GitHub repo
repo_name: 'GitHub'
edit_uri: 'edit/main/docs/'  # Kullanıcıların GitHub üzerinden döküman düzenlemesi için link

# Sayfa Başlıkları İçin Varsayılan Ayarlar
use_directory_urls: true  # URL'ler sonunda .html olmadan
extra_css:
  - 'stylesheets/custom.css'  # Özel CSS
extra_javascript:
  - 'javascripts/custom.js'  # Özel JavaScript

# GitHub Pages Konfigürasyonu
site_dir: 'site'  # Statik dosyaların oluşturulacağı dizin

copyright: >
  Copyright &copy; 2023 - 2024 Kerim Turak –
  <a href="#__consent">Change cookie settings</a>